### ISSUE TITLE
ValueError: [E098] Trying to set conflicting doc.ents: '(0, 1, 'ORG')' and '(0, 1, '')'. A token can only be part of one entity, so make sure the entities you're setting don't overlap.

### ISSUE THREAD

**Issue by haiya1994** [mpuig/spacy-lookup#11]
ValueError: [E098] Trying to set conflicting doc.ents: '(0, 1, 'ORG')' and '(0, 1, '')'. A token can only be part of one entity, so make sure the entities you're setting don't overlap.

My code is:

import spacy
from spacy_lookup import Entity

nlp = spacy.load('en')
entity = Entity(keywords_list=['Digitoxin'])
nlp.add_pipe(entity, last=True)

doc = nlp(u"Digitoxin metabolism by rat liver microsomes .")

print(doc._.entities)

**Comment by rbhambriiit** [comment]
I faced a similar issue with latest v2.0.18

pip install spacy==2.0.13
resolves the issue for me.

**Comment by sagarkarnati** [comment]
worked with spacy==2.0.13 for me

**Comment by yu45020** [comment]
I am using 2.0.18. Based on its [doc](https://spacy.io/usage/rule-based-matching#entityruler-usage)

> The entity ruler is designed to integrate with spaCy’s existing statistical models and enhance the named entity recognizer. If it’s added before the "ner" component, the entity recognizer will respect the existing entity spans and adjust its predictions around it. This can significantly improve accuracy in some cases. If it’s added after the "ner" component, the entity ruler will only add spans to the doc.ents if they don’t overlap with existing entities predicted by the model. To overwrite overlapping entities, you can set overwrite_ents=True on initialization.

I have no problems when I use this:
```Python
entity = Entity(keywords_list=user_dict)
nlp.add_pipe(entity, before='ner')
```

**Comment by kavetinaveen** [comment]
I think switching back to earlier version won't throw error but it's not resolving your issue. Actual issue is with conflicting entities. For example, 'Jon' is mapped to 'Name' and 'Jon Snow' is also mapped to 'Name'. I am facing same issue, suggest if there is any solution for this. I have many such conflicting tokens in my dictionary :(
