### ISSUE TITLE
Finding keywords on lemmas?

### ISSUE THREAD

**Issue by PAK90** [mpuig/spacy-lookup#14]
I'm using this library and it works great, but there are occasions when I'm looking for the pluralized version of a word to be recognised, e.g. `mouldy green apples`. If I have `apple` as an added keyword, it won't find `apple` in that example sentence. Is there a way to have the keyword be found on the lemma of `apples`, i.e. `apple`?

**Comment by mpuig** [comment]
@PAK90 you can create a new version of the text using the lemmas and use it as a source for the library:

```
lemmas = ' '.join([token.lemma_ for token in doc])
doc = nlp(lemmas)
print([(token.text, token._.canonical) for token in doc if token._.is_entity])
```
