### ISSUE TITLE
How to retrieve native spacy functionality for type 'Entity'

### ISSUE THREAD

**Issue by chaxor** [mpuig/spacy-lookup#2]
I do not know a great deal about spacy, but it appears that you are rewriting the Entity object for spacy here, which may cause issues with trying to use spacy functions after the dictionary match.

I have provided an example below of the trouble I'm having. 

I was attempting to use the spacy 'GoldParse' to get performance measures after including a dictionary to improve my trained NER model.

Any idea how to fix the fact that spacy now thinks there is not an entity?

```
      9         if annot is None:
     10             annot = []
---> 11         doc = nlp_model(input_)
     12         gold = GoldParse(doc, entities = annot)
     13         try:

~/.local/lib/python3.6/site-packages/spacy/language.py in __call__(self, text, disable)
    350             if not hasattr(proc, '__call__'):
    351                 raise ValueError(Errors.E003.format(component=type(proc), name=name))
--> 352             doc = proc(doc)
    353             if doc is None:
    354                 raise ValueError(Errors.E005.format(name=name))

~/.local/lib/python3.6/site-packages/spacy_lookup/__init__.py in __call__(self, doc)
     38         for _, start, end in matches:
     39             entity = doc.char_span(start, end, label=self.label)
---> 40             for token in entity:
     41                 token._.set(self._is_entity, True)
     42             spans.append(entity)

TypeError: 'NoneType' object is not iterable
```

**Comment by jamesdunham** [comment]
`Doc.char_span()` returns `None` if the span is invalid. This would happen, for example, if either index didn't coincide with the start or end of a token. That's almost certainly what's happening here. `spacy_lookup` merges multiple tokens in a successful lookup, and an attempt to slice into the document where one of the component tokens previously started or ended fails.

**Comment by mpuig** [comment]
This was fixed with https://github.com/mpuig/spacy-lookup/pull/1 but it wasn't updated to pypi. Now it's done and it should work.
