### ISSUE TITLE
Could merging spans after successful lookups be avoided or optional?

### ISSUE THREAD

**Issue by jamesdunham** [mpuig/spacy-lookup#5]
Hi, I've been very happy to discover this contribution to the spacy ecosystem.

I wanted to write up an issue I encountered during evaluation of a model that included an Entity component. It's probably the cause of #2.

```
import spacy
from spacy.scorer import Scorer
from spacy_lookup import Entity

nlp = spacy.blank('en')
text = 'The Chamber of Commerce testified in support.'
```

For use later as a gold parse, create a Doc from the blank model:
```
gold = nlp(text)
```

Run the lookup:
```
entity = Entity(nlp, keywords_list=['Chamber of Commerce'], label='ORG')
nlp.add_pipe(entity, last=True)
doc = nlp(text)

# Successful
assert doc.ents[0].text == 'Chamber of Commerce'
```

As the readme mentions, a multi-token entity span will be merged after a successful lookup. This means our two documents (processed and gold) have diverged.
```
assert doc[1].text == 'Chamber of Commerce'
assert gold[1].text == 'Chamber'
```

When calling the evaluate() method of a Language instance, this will eventually happen (simplified from the actual source):
```
scorer = Scorer()
scorer.score(doc, gold, verbose=True)
# ValueError: [E078] Error computing score: number of words in Doc (6) does not equal number of words in GoldParse (8).
```

There's unfortunately no `Span.split()` method, so this isn't easily reversible.

**Comment by mpuig** [comment]
As you mention in your detailed explanation, once the plugin is used, the text can change if entities are found:
```
assert doc[1].text == 'Chamber of Commerce'
assert gold[1].text == 'Chamber'
```
So it changes the number of words too.
