### ISSUE TITLE
TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by agnesbao** [mpuig/spacy-lookup#7]
Hello, 

I tend to run into this error at "spacy_lookup\__init__.py" line 60, 

doc.ents = list(doc.ents) + [entity]

Looks like line 58 and line 60 is incorrectly indented. It should be inside of "if entity:"

Please check if this is the case. I can get around the error by indenting the two lines. 

Thanks,
Agnes

**Comment by mpuig** [comment]
This should be solved in the latest release. Thanks!
