### ISSUE TITLE
TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by masoodimran** [mpuig/spacy-lookup#9]
For some of the data, I keep getting this error. I tried to indent the code as suggested in https://github.com/mpuig/spacy-lookup/issues/7, but it did not work.
__________________________________
flashtext        2.7 
spacy            2.0.16    
spacy-lookup     0.0.3
__________________________________
Any suggestions please?
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-186-a246bb649ba7> in <module>
----> 1 doc = nlp(data)
      2 
      3 print(doc._.entities)
      4 for ent in doc.ents:
      5     print((ent.text, ent.start_char, ent.end_char, ent.label_))

~/.virtualenvs/spacy_lookup/lib/python3.6/site-packages/spacy/language.py in __call__(self, text, disable)
    344             if not hasattr(proc, '__call__'):
    345                 raise ValueError(Errors.E003.format(component=type(proc), name=name))
--> 346             doc = proc(doc)
    347             if doc is None:
    348                 raise ValueError(Errors.E005.format(name=name))

~/.virtualenvs/spacy_lookup/lib/python3.6/site-packages/spacy_lookup/__init__.py in __call__(self, doc)
     53             spans.append(entity)
     54             # Overwrite doc.ents and add entity – be careful not to replace!
---> 55             doc.ents = list(doc.ents) + [entity]
     56 
     57 

doc.pyx in spacy.tokens.doc.Doc.ents.__set__()

TypeError: object of type 'NoneType' has no len()

**Comment by mpuig** [comment]
With the new version should work.

**Comment by nidhit216** [comment]
Hi mpuig!
Still facing this issue with the latest version (spacy==2.0.18)
Please help?
